const API = localStorage.getItem('pf_api') || 'http://localhost:8000';
let sessionId=localStorage.getItem('pf_session')||null; let questions=[]; let answers={}; let qIndex=0; let challenge=null;
async function api(path,opts={}){const res=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!res.ok){let m='Request failed';try{m=(await res.json()).detail||m}catch{}throw new Error(m)}return res.json()}
async function ensureSession(){if(!sessionId){const r=await api('/api/session',{method:'POST',body:JSON.stringify({})});sessionId=r.session_id;localStorage.setItem('pf_session',sessionId)}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dimLabel(k){return k.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}
function renderResult(r, target, retry=true){target.innerHTML=`<div class="result"><div class="score-card"><div><div class="score">${r.score}<small>/100</small></div><b>${esc(r.level)}</b></div><div class="pill">${retry?'Now try again':'Result'}</div></div><div class="bars">${Object.entries(r.dimensions).map(([k,v])=>`<div class="bar"><span>${dimLabel(k)}</span><div class="track"><div class="fill" style="width:${v}%"></div></div><b>${v}</b></div>`).join('')}</div><div class="feedback"><strong>What to fix</strong>${esc((r.weaknesses||[]).join(' · '))}</div><div class="feedback"><strong>Why</strong>${esc(r.explanation)}</div><div class="feedback"><strong>Improved version</strong><div style="white-space:pre-wrap">${esc(r.improved_prompt)}</div></div>${retry?`<button id="retry-btn" class="button primary" style="margin-top:14px">Rewrite it yourself</button><div id="retry-area"></div>`:''}</div>`;
if(retry)document.getElementById('retry-btn').onclick=()=>{document.getElementById('retry-area').innerHTML=`<textarea id="retry-input" maxlength="4000" placeholder="Rewrite your prompt using the feedback..."></textarea><div class="row"><span></span><button id="retry-submit" class="button primary">Score my retry</button></div>`;document.getElementById('retry-submit').onclick=async()=>{try{const rr=await api('/api/coach/retry',{method:'POST',body:JSON.stringify({session_id:sessionId,prompt:document.getElementById('retry-input').value,previous_score:r.score})});renderResult(rr,target,false);loadProgress()}catch(e){alert(e.message)}}}}
async function loadTest(){await ensureSession();questions=await api('/api/skill-test/questions');renderQuestion()}
function renderQuestion(){const q=questions[qIndex];document.getElementById('test-progress').textContent=`${qIndex+1} / ${questions.length}`;const body=document.getElementById('test-body');let html=`<div class="question"><h3>${esc(q.text)}</h3>`;if(q.type==='scenario_mcq'){const opts=[['a','A'],['b','B'],['c','C'],['d','D']];html+=opts.map(([id,label],i)=>`<button class="option ${answers[q.id]===id?'selected':''}" data-id="${id}">${label}. ${esc(q.options[i])}</button>`).join('')}else html+=`<textarea id="answer" maxlength="4000" placeholder="Write the prompt you would give an AI..."></textarea>`;html+=`<div class="row"><span>${q.competency.replaceAll('_',' ')}</span><button id="next" class="button primary">${qIndex===questions.length-1?'Submit test':'Next'}</button></div></div>`;body.innerHTML=html;if(q.type==='scenario_mcq')document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{answers[q.id]=b.dataset.id;renderQuestion()});else document.getElementById('answer').value=answers[q.id]||'';document.getElementById('next').onclick=async()=>{if(q.type==='prompt_write')answers[q.id]=document.getElementById('answer').value.trim();if(!answers[q.id])return alert('Answer this question first.');if(qIndex<questions.length-1){qIndex++;renderQuestion()}else submitTest()}}
async function submitTest(){try{const r=await api('/api/skill-test/submit',{method:'POST',body:JSON.stringify({session_id:sessionId,answers:Object.entries(answers).map(([question_id,answer])=>({question_id,answer}))})});renderResult(r,document.getElementById('test-body'),false);loadProgress()}catch(e){alert(e.message)}}
async function coach(){const input=document.getElementById('coach-input');if(input.value.trim().length<3)return alert('Write a real prompt first.');const b=document.getElementById('coach-submit');b.disabled=true;b.textContent='Analysing…';try{await ensureSession();const r=await api('/api/coach/evaluate',{method:'POST',body:JSON.stringify({session_id:sessionId,prompt:input.value})});renderResult(r,document.getElementById('coach-result'));loadProgress()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='Analyse my prompt'}}
async function loadChallenge(){try{await ensureSession();challenge=await api('/api/challenge/today');document.getElementById('challenge-card').innerHTML=`<div class="challenge-meta">${esc(challenge.category)} · ${esc(challenge.difficulty)}</div><h3>${esc(challenge.title)}</h3><p>${esc(challenge.scenario)}</p><textarea id="challenge-input" maxlength="4000" placeholder="Write your prompt..."></textarea><div class="row"><span></span><button id="challenge-submit" class="button primary">Submit challenge</button></div><div id="challenge-result"></div>`;document.getElementById('challenge-submit').onclick=async()=>{try{const r=await api('/api/challenge/submit',{method:'POST',body:JSON.stringify({session_id:sessionId,challenge_id:challenge.id,prompt:document.getElementById('challenge-input').value})});renderResult(r,document.getElementById('challenge-result'),false);loadProgress()}catch(e){alert(e.message)}}}catch(e){document.getElementById('challenge-card').textContent=e.message}}
async function loadProgress(){if(!sessionId)return;try{const p=await api('/api/progress?session_id='+encodeURIComponent(sessionId));const events=p.events||[];if(!events.length)return;const max=Math.max(...events.map(x=>x.score),100);document.getElementById('progress-body').innerHTML=`<div class="progress-grid"><div class="stat"><span>Current score</span><br><b>${p.current_score}</b></div><div class="stat"><span>Total improvement</span><br><b>${p.improvement>0?'+':''}${p.improvement||0}</b></div><div class="stat"><span>Scored attempts</span><br><b>${events.length}</b></div></div><div class="timeline">${events.slice(-18).map(e=>`<div class="point" title="${e.event_type}: ${e.score}" style="height:${Math.max(8,e.score/max*130)}px"><span>${e.score}</span></div>`).join('')}</div>`}catch{}}
document.getElementById('coach-input').addEventListener('input',e=>document.getElementById('char-count').textContent=`${e.target.value.length} / 4000`);document.getElementById('coach-submit').onclick=coach;
loadTest();loadChallenge();loadProgress();
