QUESTIONS = [
{"id":"q1","type":"prompt_write","competency":"context","text":"You are a final-year IT student applying for a junior IT support role. Write a prompt that asks AI to improve your CV for that role.","scenario":"Improve a CV for a junior IT support role."},
{"id":"q2","type":"prompt_write","competency":"task_clarity","text":"You have a long lecture transcript. Write a prompt that clearly tells an AI exactly what you want it to do with the transcript.","scenario":"Turn a lecture transcript into useful study material."},
{"id":"q3","type":"prompt_write","competency":"specificity","text":"Write a prompt that asks AI to create a 7-day study plan for a difficult exam. Include enough concrete detail to reduce guesswork.","scenario":"Create a seven-day exam study plan."},
{"id":"q4","type":"prompt_write","competency":"constraints","text":"Write a prompt for rewriting a professional email. Add sensible boundaries so the result stays useful and accurate.","scenario":"Rewrite a professional email while preserving facts."},
{"id":"q5","type":"prompt_write","competency":"output_format","text":"Write a prompt asking AI to compare two job offers. Specify exactly how you want the answer structured.","scenario":"Compare two job offers in a decision-friendly format."},
{"id":"q6","type":"prompt_write","competency":"examples","text":"Write a prompt asking AI to generate three social-media captions in a particular style. Include an example that demonstrates the style you want.","scenario":"Generate captions using a demonstrated style."},
{"id":"q7","type":"prompt_write","competency":"evaluation","text":"Write a prompt asking AI to summarise research while reducing the risk of invented facts. Include a verification requirement.","scenario":"Summarise research with verification and uncertainty handling."},
{"id":"q8","type":"scenario_mcq","competency":"workflow_thinking","text":"You ask AI for a report, receive a draft, then blindly submit it. What is the strongest improvement?","options":["Ask AI to make it longer","Add a verification/review step before submission","Use more emojis","Ask AI to call itself an expert"],"answer":"b"},
{"id":"q9","type":"scenario_mcq","competency":"critical_evaluation","text":"AI gives you a precise statistic but no source. What should you do first?","options":["Assume it is correct","Ask for verification and independently check the source","Delete the whole answer","Ask for a longer explanation"],"answer":"b"},
{"id":"q10","type":"scenario_mcq","competency":"iteration","text":"Your first AI result is close but not useful. What is the strongest next step?","options":["Start over randomly","Add targeted feedback and constraints, then retry","Blame the model","Use the exact same prompt again"],"answer":"b"},
]
